package me.ayunami2000.fabricnotebot;

import net.minecraft.block.Block;
import net.minecraft.block.Blocks;

public class ImageBlocks {
    public static Block[] blocks=new Block[]{
            Blocks.ACACIA_LOG,
            Blocks.ACACIA_PLANKS,
            Blocks.ANCIENT_DEBRIS,
            Blocks.ANDESITE,
            Blocks.BASALT,
            Blocks.BEDROCK,
            Blocks.BIRCH_LOG,
            Blocks.BIRCH_PLANKS,
            Blocks.BLACK_CONCRETE,
            Blocks.BLACK_GLAZED_TERRACOTTA,
            Blocks.BLACK_TERRACOTTA,
            Blocks.BLACK_WOOL,
            Blocks.BLACKSTONE,
            Blocks.BLUE_CONCRETE,
            Blocks.BLUE_GLAZED_TERRACOTTA,
            Blocks.BLUE_ICE,
            Blocks.BLUE_TERRACOTTA,
            Blocks.BLUE_WOOL,
            Blocks.BONE_BLOCK,
            //Blocks.BOOKSHELF,
            Blocks.BRICKS,
            Blocks.BROWN_CONCRETE,
            Blocks.BROWN_GLAZED_TERRACOTTA,
            Blocks.BROWN_MUSHROOM_BLOCK,
            Blocks.BROWN_TERRACOTTA,
            Blocks.BROWN_WOOL,
            Blocks.CHISELED_NETHER_BRICKS,
            Blocks.CHISELED_POLISHED_BLACKSTONE,
            Blocks.CHISELED_QUARTZ_BLOCK,
            Blocks.CHISELED_RED_SANDSTONE,
            Blocks.CHISELED_SANDSTONE,
            Blocks.CHISELED_STONE_BRICKS,
            Blocks.CLAY,
            Blocks.COAL_BLOCK,
            //Blocks.COAL_ORE,//remove
            Blocks.COARSE_DIRT,
            Blocks.COBBLESTONE,
            Blocks.CRACKED_NETHER_BRICKS,
            Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS,
            Blocks.CRACKED_STONE_BRICKS,
            Blocks.CRIMSON_PLANKS,
            Blocks.CRIMSON_STEM,
            Blocks.CRYING_OBSIDIAN,
            Blocks.CUT_RED_SANDSTONE,
            Blocks.CUT_SANDSTONE,
            Blocks.CYAN_CONCRETE,
            Blocks.CYAN_GLAZED_TERRACOTTA,
            Blocks.CYAN_TERRACOTTA,
            Blocks.CYAN_WOOL,
            Blocks.DARK_OAK_LOG,
            Blocks.DARK_OAK_PLANKS,
            Blocks.DARK_PRISMARINE,
            Blocks.DEAD_BRAIN_CORAL_BLOCK,
            Blocks.DEAD_BUBBLE_CORAL_BLOCK,
            Blocks.DEAD_FIRE_CORAL_BLOCK,
            Blocks.DEAD_HORN_CORAL_BLOCK,
            Blocks.DEAD_TUBE_CORAL_BLOCK,
            Blocks.DIAMOND_BLOCK,
            //Blocks.DIAMOND_ORE,//remove
            Blocks.DIORITE,
            Blocks.DIRT,
            Blocks.EMERALD_BLOCK,
            //Blocks.EMERALD_ORE,//remove
            Blocks.END_STONE,
            Blocks.END_STONE_BRICKS,
            Blocks.GILDED_BLACKSTONE,
            Blocks.GLOWSTONE,
            Blocks.GOLD_BLOCK,
            //Blocks.GOLD_ORE,//remove
            Blocks.GRANITE,
            Blocks.GRAY_CONCRETE,
            Blocks.GRAY_GLAZED_TERRACOTTA,
            Blocks.GRAY_TERRACOTTA,
            Blocks.GRAY_WOOL,
            Blocks.GREEN_CONCRETE,
            Blocks.GREEN_GLAZED_TERRACOTTA,
            Blocks.GREEN_TERRACOTTA,
            Blocks.GREEN_WOOL,
            Blocks.HAY_BLOCK,
            Blocks.HONEY_BLOCK,
            Blocks.HONEYCOMB_BLOCK,
            Blocks.IRON_BLOCK,
            //Blocks.IRON_ORE,//remove
            Blocks.JUNGLE_LOG,
            Blocks.JUNGLE_PLANKS,
            Blocks.LAPIS_BLOCK,
            //Blocks.LAPIS_ORE,//remove
            Blocks.LIGHT_BLUE_CONCRETE,
            Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA,
            Blocks.LIGHT_BLUE_TERRACOTTA,
            Blocks.LIGHT_BLUE_WOOL,
            Blocks.LIGHT_GRAY_CONCRETE,
            Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA,
            Blocks.LIGHT_GRAY_TERRACOTTA,
            Blocks.LIGHT_GRAY_WOOL,
            Blocks.LIME_CONCRETE,
            Blocks.LIME_GLAZED_TERRACOTTA,
            Blocks.LIME_TERRACOTTA,
            Blocks.LIME_WOOL,
            Blocks.MAGENTA_CONCRETE,
            Blocks.MAGENTA_GLAZED_TERRACOTTA,
            Blocks.MAGENTA_TERRACOTTA,
            Blocks.MAGENTA_WOOL,
            Blocks.MAGMA_BLOCK,
            Blocks.MELON,
            Blocks.MOSSY_COBBLESTONE,
            Blocks.MOSSY_STONE_BRICKS,
            Blocks.MUSHROOM_STEM,
            Blocks.MYCELIUM,
            Blocks.NETHER_BRICKS,
            //Blocks.NETHER_GOLD_ORE,//remove
            //Blocks.NETHER_QUARTZ_ORE,//remove
            Blocks.NETHER_WART_BLOCK,
            Blocks.NETHERITE_BLOCK,
            Blocks.NETHERRACK,
            Blocks.OAK_LOG,
            Blocks.OAK_PLANKS,
            Blocks.OBSIDIAN,
            Blocks.ORANGE_CONCRETE,
            Blocks.ORANGE_GLAZED_TERRACOTTA,
            Blocks.ORANGE_TERRACOTTA,
            Blocks.ORANGE_WOOL,
            Blocks.PACKED_ICE,
            Blocks.PINK_CONCRETE,
            Blocks.PINK_GLAZED_TERRACOTTA,
            Blocks.PINK_TERRACOTTA,
            Blocks.PINK_WOOL,
            Blocks.POLISHED_ANDESITE,
            Blocks.POLISHED_BASALT,
            Blocks.POLISHED_BLACKSTONE,
            Blocks.POLISHED_BLACKSTONE_BRICKS,
            Blocks.POLISHED_DIORITE,
            Blocks.POLISHED_GRANITE,
            Blocks.PRISMARINE,
            Blocks.PRISMARINE_BRICKS,
            Blocks.PUMPKIN,
            Blocks.PURPLE_CONCRETE,
            Blocks.PURPLE_GLAZED_TERRACOTTA,
            Blocks.PURPLE_TERRACOTTA,
            Blocks.PURPLE_WOOL,
            Blocks.PURPUR_BLOCK,
            Blocks.PURPUR_PILLAR,
            Blocks.QUARTZ_BLOCK,
            Blocks.QUARTZ_BRICKS,
            Blocks.QUARTZ_PILLAR,
            Blocks.RED_CONCRETE,
            Blocks.RED_GLAZED_TERRACOTTA,
            Blocks.RED_MUSHROOM_BLOCK,
            Blocks.RED_NETHER_BRICKS,
            Blocks.RED_SANDSTONE,
            Blocks.RED_TERRACOTTA,
            Blocks.RED_WOOL,
            Blocks.REDSTONE_BLOCK,
            //Blocks.REDSTONE_ORE,//remove
            Blocks.SANDSTONE,
            //Blocks.SEA_LANTERN,
            Blocks.SHROOMLIGHT,
            Blocks.SLIME_BLOCK,
            Blocks.SMOOTH_STONE,
            Blocks.SNOW_BLOCK,
            Blocks.SOUL_SAND,
            Blocks.SOUL_SOIL,
            Blocks.SPONGE,
            Blocks.SPRUCE_LOG,
            Blocks.SPRUCE_PLANKS,
            Blocks.STONE,
            Blocks.STONE_BRICKS,
            Blocks.STRIPPED_ACACIA_LOG,
            Blocks.STRIPPED_BIRCH_LOG,
            Blocks.STRIPPED_CRIMSON_STEM,
            Blocks.STRIPPED_DARK_OAK_LOG,
            Blocks.STRIPPED_JUNGLE_LOG,
            Blocks.STRIPPED_OAK_LOG,
            Blocks.STRIPPED_SPRUCE_LOG,
            Blocks.STRIPPED_WARPED_STEM,
            //Blocks.TARGET,
            Blocks.TERRACOTTA,
            Blocks.WARPED_PLANKS,
            Blocks.WARPED_STEM,
            Blocks.WARPED_WART_BLOCK,
            Blocks.WHITE_CONCRETE,
            Blocks.WHITE_GLAZED_TERRACOTTA,
            Blocks.WHITE_TERRACOTTA,
            Blocks.WHITE_WOOL,
            Blocks.YELLOW_CONCRETE,
            Blocks.YELLOW_GLAZED_TERRACOTTA,
            Blocks.YELLOW_TERRACOTTA,
            Blocks.YELLOW_WOOL
    };
    public static Integer[][] blockRGB=new Integer[][]{
            new Integer[]{108, 100, 92},
            new Integer[]{140, 69, 44},
            new Integer[]{100, 68, 68},
            new Integer[]{140, 140, 140},
            new Integer[]{76, 76, 76},
            new Integer[]{100, 100, 100},
            new Integer[]{220, 220, 204},
            new Integer[]{157, 141, 100},
            new Integer[]{12, 12, 20},
            new Integer[]{31, 31, 35},
            new Integer[]{36, 28, 20},
            new Integer[]{26, 28, 29},
            new Integer[]{36, 36, 28},
            new Integer[]{44, 44, 140},
            new Integer[]{36, 28, 63},
            new Integer[]{116, 172, 252},
            new Integer[]{76, 60, 92},
            new Integer[]{58, 60, 164},
            new Integer[]{228, 227, 211},
            //new Integer[]{39, 85, 100},
            new Integer[]{123, 67, 52},
            new Integer[]{100, 60, 36},
            new Integer[]{20, 119, 140},
            new Integer[]{148, 116, 84},
            new Integer[]{76, 52, 36},
            new Integer[]{125, 78, 45},
            new Integer[]{32, 16, 20},
            new Integer[]{60, 60, 68},
            new Integer[]{236, 232, 224},
            new Integer[]{198, 108, 36},
            new Integer[]{223, 218, 174},
            new Integer[]{96, 96, 96},
            new Integer[]{172, 172, 188},
            new Integer[]{20, 20, 20},
            //new Integer[]{62, 62, 62},
            new Integer[]{121, 83, 59},
            new Integer[]{140, 132, 140},
            new Integer[]{49, 25, 28},
            new Integer[]{36, 36, 28},
            new Integer[]{124, 120, 124},
            new Integer[]{108, 52, 76},
            new Integer[]{84, 28, 20},
            new Integer[]{66, 4, 143},
            new Integer[]{199, 108, 36},
            new Integer[]{223, 215, 170},
            new Integer[]{20, 124, 140},
            new Integer[]{62, 69, 74},
            new Integer[]{92, 92, 92},
            new Integer[]{20, 128, 140},
            new Integer[]{60, 52, 28},
            new Integer[]{45, 28, 12},
            new Integer[]{60, 107, 91},
            new Integer[]{156, 148, 140},
            new Integer[]{116, 108, 100},
            new Integer[]{158, 153, 145},
            new Integer[]{114, 106, 100},
            new Integer[]{158, 152, 144},
            new Integer[]{101, 245, 236},
            //new Integer[]{156, 250, 236},
            new Integer[]{164, 164, 164},
            new Integer[]{124, 84, 60},
            new Integer[]{100, 244, 152},
            //new Integer[]{120, 120, 120},
            new Integer[]{220, 228, 164},
            new Integer[]{181, 173, 125},
            new Integer[]{34, 32, 28},
            new Integer[]{252, 220, 116},
            new Integer[]{252, 228, 72},
            //new Integer[]{252, 246, 145},
            new Integer[]{84, 60, 48},
            new Integer[]{52, 60, 60},
            new Integer[]{150, 150, 150},
            new Integer[]{60, 44, 36},
            new Integer[]{60, 68, 68},
            new Integer[]{76, 92, 36},
            new Integer[]{74, 93, 37},
            new Integer[]{76, 84, 44},
            new Integer[]{82, 104, 29},
            new Integer[]{148, 132, 28},
            new Integer[]{250, 207, 95},
            new Integer[]{252, 218, 111},
            new Integer[]{231, 231, 231},
            //new Integer[]{214, 174, 150},
            new Integer[]{90, 68, 27},
            new Integer[]{182, 132, 97},
            new Integer[]{32, 72, 136},
            //new Integer[]{108, 108, 108},
            new Integer[]{36, 140, 196},
            new Integer[]{48, 159, 207},
            new Integer[]{116, 108, 140},
            new Integer[]{60, 182, 219},
            new Integer[]{124, 124, 116},
            new Integer[]{183, 188, 188},
            new Integer[]{140, 108, 100},
            new Integer[]{130, 130, 120},
            new Integer[]{92, 172, 28},
            new Integer[]{172, 236, 100},
            new Integer[]{108, 116, 52},
            new Integer[]{114, 188, 28},
            new Integer[]{172, 52, 156},
            new Integer[]{244, 180, 204},
            new Integer[]{156, 92, 109},
            new Integer[]{178, 57, 168},
            new Integer[]{242, 132, 44},
            new Integer[]{164, 172, 28},
            new Integer[]{116, 132, 84},
            new Integer[]{119, 117, 119},
            new Integer[]{212, 204, 196},
            new Integer[]{121, 101, 93},
            new Integer[]{54, 28, 29},
            //new Integer[]{252, 204, 60},
            //new Integer[]{90, 41, 36},
            new Integer[]{92, 4, 4},
            new Integer[]{56, 51, 51},
            new Integer[]{100, 44, 44},
            new Integer[]{116, 92, 52},
            new Integer[]{104, 86, 45},
            new Integer[]{20, 12, 28},
            new Integer[]{228, 100, 4},
            new Integer[]{248, 126, 24},
            new Integer[]{164, 84, 36},
            new Integer[]{248, 127, 28},
            new Integer[]{168, 199, 252},
            new Integer[]{212, 100, 140},
            new Integer[]{244, 173, 198},
            new Integer[]{164, 84, 82},
            new Integer[]{226, 114, 154},
            new Integer[]{140, 148, 148},
            new Integer[]{92, 92, 92},
            new Integer[]{52, 44, 52},
            new Integer[]{52, 44, 52},
            new Integer[]{172, 172, 172},
            new Integer[]{150, 102, 86},
            new Integer[]{104, 163, 160},
            new Integer[]{140, 200, 192},
            new Integer[]{228, 142, 32},
            new Integer[]{100, 28, 156},
            new Integer[]{44, 44, 52},
            new Integer[]{124, 76, 90},
            new Integer[]{133, 45, 181},
            new Integer[]{158, 110, 158},
            new Integer[]{196, 172, 196},
            new Integer[]{236, 236, 228},
            new Integer[]{240, 236, 232},
            new Integer[]{236, 228, 220},
            new Integer[]{140, 36, 36},
            new Integer[]{181, 44, 36},
            new Integer[]{252, 156, 156},
            new Integer[]{52, 4, 4},
            new Integer[]{209, 113, 41},
            new Integer[]{148, 68, 52},
            new Integer[]{148, 36, 36},
            new Integer[]{188, 36, 12},
            //new Integer[]{108, 108, 108},
            new Integer[]{228, 225, 185},
            //new Integer[]{210, 227, 218},
            new Integer[]{252, 211, 142},
            new Integer[]{116, 196, 100},
            new Integer[]{119, 119, 119},
            new Integer[]{244, 252, 252},
            new Integer[]{92, 68, 60},
            new Integer[]{92, 68, 60},
            new Integer[]{204, 204, 76},
            new Integer[]{77, 53, 21},
            new Integer[]{116, 84, 44},
            new Integer[]{124, 124, 124},
            new Integer[]{140, 140, 140},
            new Integer[]{175, 95, 60},
            new Integer[]{202, 180, 122},
            new Integer[]{140, 60, 92},
            new Integer[]{106, 84, 52},
            new Integer[]{172, 132, 84},
            new Integer[]{189, 152, 95},
            new Integer[]{100, 84, 49},
            new Integer[]{60, 156, 148},
            //new Integer[]{236, 212, 188},
            new Integer[]{156, 92, 68},
            new Integer[]{21, 61, 54},
            new Integer[]{68, 44, 92},
            new Integer[]{20, 124, 132},
            new Integer[]{204, 212, 212},
            new Integer[]{36, 140, 196},
            new Integer[]{212, 180, 164},
            new Integer[]{220, 223, 224},
            new Integer[]{244, 180, 20},
            new Integer[]{241, 177, 20},
            new Integer[]{188, 132, 36},
            new Integer[]{249, 195, 36}
        };
}
